github: [DeltaDinizzz]
patreon: DeltaDinizzz
open_collective: rustcenter
ko_fi: deltadinizzz
tidelift: npm/rustcenter
community_bridge: rustcenter
liberapay: DeltaFuture
issuehunt: DeltaFuture
lfx_crowdfunding: rustcenter
polar: DeltaFuture
buy_me_a_coffee: DeltaFuture
thanks_dev: u/gh/DeltaDinizzz
custom: ["https://rustcenter.org"]
